#!/bin/bash
set -e
###-------------------------------------------------------------------
### File    : create_xabber_server
### Author  : Andrey Gagarin <andrey.gagarin@redsolution.com>
### Created : 16 Jul 2018 by Andrey Gagarin <andrey.gagarin@redsolution.com>
###
###
### Copyright (C) 2007-2019   Redsolution OÜ
###
### This program is free software: you can redistribute it and/or
### modify it under the terms of the GNU Affero General Public License as
### published by the Free Software Foundation, either version 3 of the
### License, or (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
### General Public License for more details.
###-------------------------------------------------------------------

function get_xabber_web() {
cd $root_dir
rm -fr xabber-web
echo "Get a new custom xabber web"
git clone https://github.com/redsolution/xabber-web.git
cd xabber-web
git checkout develop
cp -r $root_dir/xabber-web/images/ $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/fonts/ $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/dist/ $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/sounds/ $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/css/ $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/firebase-messaging-sw.js $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/manifest.json $panel_dir/static/xabberweb/
cp -r $root_dir/xabber-web/version.js $panel_dir/static/xabberweb/
}

function get_makeself() {
if [ -d "makeself" ]; then
    echo "Makeself is already installed"
else
    git clone https://github.com/redsolution/makeself.git
fi
}

function install_new_ui() {
echo "Clone new builder"
cd $root_dir
rm -fr panel-builder
git clone gitolite3@git.redsolution.ru:/xabber/xmppserver/panel-builder
cd panel-builder
make
mkdir -p $panel_dir
rsync -aHv dist/xabber-server/ $panel_dir/
cd $panel_dir
echo "Start migration"
./xabber-server migrate
}


function get_xabberxmppserver() {
echo "Get xabber-xmpp-server"
rm -fr xabber-xmpp-server
git clone https://github.com/redsolution/xabber-xmpp-server.git xabber-xmpp-server
cd xabber-xmpp-server
git checkout new_stanzas
./autogen.sh
./configure --enable-pgsql
make
echo "make rel"
make clean-rel
make rel
cd $root_dir
mkdir -p $xmppserver_dir
rsync -aH xabber-xmpp-server/rel/ejabberd/ $xmppserver_dir/
}

root_dir=$(pwd)
rel_dir=$root_dir/rel
panel_dir=$rel_dir/panel
xmppserver_dir=$rel_dir/xmppserver
rm -fr $rel_dir
mkdir $rel_dir
get_makeself
makeself=$root_dir/makeself/makeself.sh
get_xabberxmppserver
erts_path=$(find $xmppserver_dir -name "erts*" -type d)
erts_version=$(echo $erts_path | awk -F "/" '{print $NF}')
EXP00="s#ERTS_VER#$erts_version#g"
install_new_ui
echo "Copy system libs and psql libs"
cp -r $root_dir/xabber-server-files/psql_stuff/* $rel_dir/
cp -r $root_dir/xabber-xmpp-server/db_migration $rel_dir/
cp -r $root_dir/xabber-xmpp-server/config_migrations $rel_dir/
cp $root_dir/xabber-xmpp-server/version $rel_dir/
cp $root_dir/xabber-server-files/setup.sh $rel_dir/
cp $root_dir/xabber-server-files/dig $rel_dir/
cp $root_dir/xabber-server-files/xabber.text $rel_dir/
cp $root_dir/xabber-server-files/server.pem $rel_dir/
cp $root_dir/xabber-server-files/001-site.conf $rel_dir/
cp $root_dir/xabber-server-files/001-site-default.conf $rel_dir/
cp $root_dir/xabber-server-files/001-site-ssl.conf $rel_dir/
cp $root_dir/xabber-server-files/well-known.apache $rel_dir/
cp $root_dir/xabber-server-files/xabberserver.service0 $rel_dir/
cp $root_dir/xabber-server-files/xabber_server.ini0 $rel_dir/
cp $root_dir/xabber-server-files/erl $erts_path/bin/erl
sh -c "sed -e $EXP00 <$root_dir/xabber-server-files/ejabberdctl >$xmppserver_dir/bin/ejabberdctl"
cp -r $root_dir/xabber-server-files/linux/* $xmppserver_dir/lib/
rm $xmppserver_dir/etc/ejabberd/ejabberd.yml
get_xabber_web
cd $root_dir
$makeself $rel_dir xabberserver_installer.bin "Xabber Server Installer" ./setup.sh
